/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author souls
 */
public class GestionPrestamosVista extends javax.swing.JFrame {

    /**
     * Creates new form GestionLibrosVista
     */
    public GestionPrestamosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_gestion_libros = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_id_socio = new javax.swing.JTextField();
        txt_id_libro = new javax.swing.JTextField();
        txt_fecha_prestamo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_devolver = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        btn_pagos_multas = new javax.swing.JButton();

        btn_gestion_libros.setBackground(new java.awt.Color(65, 237, 206));
        btn_gestion_libros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gestion_libros.setText("Gestión de Libros");
        btn_gestion_libros.setBorder(new javax.swing.border.MatteBorder(null));
        btn_gestion_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_librosActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de libros");

        jPanel1.setBackground(new java.awt.Color(116, 223, 190));

        txt_id_socio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_id_socio.setToolTipText("");
        txt_id_socio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_id_socio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_id_libro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_id_libro.setToolTipText("");
        txt_id_libro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_id_libro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_fecha_prestamo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_fecha_prestamo.setToolTipText("");
        txt_fecha_prestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_fecha_prestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Préstamo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID del Libro:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID del Socio:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Gestion Prestamos");

        btn_devolver.setBackground(new java.awt.Color(65, 237, 206));
        btn_devolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_devolver.setText("Devolver");
        btn_devolver.setBorder(new javax.swing.border.MatteBorder(null));
        btn_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolverActionPerformed(evt);
            }
        });

        btn_registrar.setBackground(new java.awt.Color(65, 237, 206));
        btn_registrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(new javax.swing.border.MatteBorder(null));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_pagos_multas.setBackground(new java.awt.Color(65, 237, 206));
        btn_pagos_multas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_pagos_multas.setText("Pagos y Multas");
        btn_pagos_multas.setBorder(new javax.swing.border.MatteBorder(null));
        btn_pagos_multas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagos_multasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_pagos_multas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fecha_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id_socio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(228, 228, 228)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_socio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fecha_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_pagos_multas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gestion_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gestion_librosActionPerformed

    private void btn_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_devolverActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_pagos_multasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagos_multasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pagos_multasActionPerformed

    public JButton getBtn_devolver() {
        return btn_devolver;
    }

    public void setBtn_devolver(JButton btn_devolver) {
        this.btn_devolver = btn_devolver;
    }

    public JButton getBtn_gestion_libros() {
        return btn_gestion_libros;
    }

    public void setBtn_gestion_libros(JButton btn_gestion_libros) {
        this.btn_gestion_libros = btn_gestion_libros;
    }

    public JButton getBtn_pagos_multas() {
        return btn_pagos_multas;
    }

    public void setBtn_pagos_multas(JButton btn_pagos_multas) {
        this.btn_pagos_multas = btn_pagos_multas;
    }

    public JButton getBtn_registrar() {
        return btn_registrar;
    }

    public void setBtn_registrar(JButton btn_registrar) {
        this.btn_registrar = btn_registrar;
    }


    public JTextField getTxt_fecha_prestamo() {
        return txt_fecha_prestamo;
    }

    public void setTxt_fecha_prestamo(JTextField txt_fecha_prestamo) {
        this.txt_fecha_prestamo = txt_fecha_prestamo;
    }

    public JTextField getTxt_id_libro() {
        return txt_id_libro;
    }

    public void setTxt_id_libro(JTextField txt_id_libro) {
        this.txt_id_libro = txt_id_libro;
    }

    public JTextField getTxt_id_socio() {
        return txt_id_socio;
    }

    public void setTxt_id_socio(JTextField txt_id_socio) {
        this.txt_id_socio = txt_id_socio;
    }
    

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_devolver;
    private javax.swing.JButton btn_gestion_libros;
    private javax.swing.JButton btn_pagos_multas;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_fecha_prestamo;
    private javax.swing.JTextField txt_id_libro;
    private javax.swing.JTextField txt_id_socio;
    // End of variables declaration//GEN-END:variables
}
