/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author souls
 */
public class GestionSociosVista extends javax.swing.JFrame {

    /**
     * Creates new form GestionLibrosVista
     */
    public GestionSociosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_gestion_libros = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_direccionSocios = new javax.swing.JTextField();
        txt_correoSocios = new javax.swing.JTextField();
        txt_nombreSocios = new javax.swing.JTextField();
        txt_telefonoSocios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_buscarSocio = new javax.swing.JButton();
        btn_eliminarSocio = new javax.swing.JButton();
        btn_registrarSocio = new javax.swing.JButton();
        btn_ver_socios = new javax.swing.JButton();
        btn_modificarSocio = new javax.swing.JButton();

        btn_gestion_libros.setBackground(new java.awt.Color(65, 237, 206));
        btn_gestion_libros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gestion_libros.setText("Gestión de Libros");
        btn_gestion_libros.setBorder(new javax.swing.border.MatteBorder(null));
        btn_gestion_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_librosActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de libros");

        jPanel1.setBackground(new java.awt.Color(116, 223, 190));

        txt_direccionSocios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_direccionSocios.setToolTipText("");
        txt_direccionSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_direccionSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_correoSocios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_correoSocios.setToolTipText("");
        txt_correoSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_correoSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_nombreSocios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nombreSocios.setToolTipText("");
        txt_nombreSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_nombreSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_telefonoSocios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_telefonoSocios.setToolTipText("");
        txt_telefonoSocios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_telefonoSocios.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefono:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Gestión Socios");

        btn_buscarSocio.setBackground(new java.awt.Color(65, 237, 206));
        btn_buscarSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_buscarSocio.setText("Buscar Socio");
        btn_buscarSocio.setBorder(new javax.swing.border.MatteBorder(null));
        btn_buscarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarSocioActionPerformed(evt);
            }
        });

        btn_eliminarSocio.setBackground(new java.awt.Color(65, 237, 206));
        btn_eliminarSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_eliminarSocio.setText("Eliminar Socio");
        btn_eliminarSocio.setBorder(new javax.swing.border.MatteBorder(null));
        btn_eliminarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarSocioActionPerformed(evt);
            }
        });

        btn_registrarSocio.setBackground(new java.awt.Color(65, 237, 206));
        btn_registrarSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_registrarSocio.setText("Registrar Socio");
        btn_registrarSocio.setBorder(new javax.swing.border.MatteBorder(null));
        btn_registrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarSocioActionPerformed(evt);
            }
        });

        btn_ver_socios.setBackground(new java.awt.Color(65, 237, 206));
        btn_ver_socios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ver_socios.setText("Ver Lista de Socios");
        btn_ver_socios.setBorder(new javax.swing.border.MatteBorder(null));
        btn_ver_socios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_sociosActionPerformed(evt);
            }
        });

        btn_modificarSocio.setBackground(new java.awt.Color(65, 237, 206));
        btn_modificarSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_modificarSocio.setText("Modificar Datos");
        btn_modificarSocio.setBorder(new javax.swing.border.MatteBorder(null));
        btn_modificarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_modificarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_registrarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_eliminarSocio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarSocio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_telefonoSocios, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_direccionSocios, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nombreSocios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_correoSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ver_socios, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccionSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefonoSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_correoSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_ver_socios, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gestion_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gestion_librosActionPerformed

    private void btn_buscarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarSocioActionPerformed

    private void btn_eliminarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarSocioActionPerformed

    private void btn_registrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarSocioActionPerformed

    private void btn_ver_sociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_sociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ver_sociosActionPerformed

    private void btn_modificarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarSocioActionPerformed

    public JButton getBtn_buscarSocio() {
        return btn_buscarSocio;
    }

    public void setBtn_buscarSocio(JButton btn_buscarSocio) {
        this.btn_buscarSocio = btn_buscarSocio;
    }

    public JButton getBtn_eliminarSocio() {
        return btn_eliminarSocio;
    }

    public void setBtn_eliminarSocio(JButton btn_eliminarSocio) {
        this.btn_eliminarSocio = btn_eliminarSocio;
    }

    public JButton getBtn_gestion_libros() {
        return btn_gestion_libros;
    }

    public void setBtn_gestion_libros(JButton btn_gestion_libros) {
        this.btn_gestion_libros = btn_gestion_libros;
    }

    public JButton getBtn_modificarSocio() {
        return btn_modificarSocio;
    }

    public void setBtn_modificarSocio(JButton btn_modificarSocio) {
        this.btn_modificarSocio = btn_modificarSocio;
    }

    public JButton getBtn_registrarSocio() {
        return btn_registrarSocio;
    }

    public void setBtn_registrarSocio(JButton btn_registrarSocio) {
        this.btn_registrarSocio = btn_registrarSocio;
    }

    public JButton getBtn_ver_socios() {
        return btn_ver_socios;
    }

    public void setBtn_ver_socios(JButton btn_ver_socios) {
        this.btn_ver_socios = btn_ver_socios;
    }

    public JTextField getTxt_correoSocios() {
        return txt_correoSocios;
    }

    public void setTxt_correoSocios(JTextField txt_correoSocios) {
        this.txt_correoSocios = txt_correoSocios;
    }

    public JTextField getTxt_direccionSocios() {
        return txt_direccionSocios;
    }

    public void setTxt_direccionSocios(JTextField txt_direccionSocios) {
        this.txt_direccionSocios = txt_direccionSocios;
    }

    public JTextField getTxt_nombreSocios() {
        return txt_nombreSocios;
    }

    public void setTxt_nombreSocios(JTextField txt_nombreSocios) {
        this.txt_nombreSocios = txt_nombreSocios;
    }

    public JTextField getTxt_telefonoSocios() {
        return txt_telefonoSocios;
    }

    public void setTxt_telefonoSocios(JTextField txt_telefonoSocios) {
        this.txt_telefonoSocios = txt_telefonoSocios;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarSocio;
    private javax.swing.JButton btn_eliminarSocio;
    private javax.swing.JButton btn_gestion_libros;
    private javax.swing.JButton btn_modificarSocio;
    private javax.swing.JButton btn_registrarSocio;
    private javax.swing.JButton btn_ver_socios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_correoSocios;
    private javax.swing.JTextField txt_direccionSocios;
    private javax.swing.JTextField txt_nombreSocios;
    private javax.swing.JTextField txt_telefonoSocios;
    // End of variables declaration//GEN-END:variables
}
