/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author souls
 */
public class GestionEmpleadosVista extends javax.swing.JFrame {

    /**
     * Creates new form GestionEmpleadosVista
     */
    public GestionEmpleadosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id_trab = new javax.swing.JTextField();
        txt_nombre_trab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_email_trab = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_ver_empleado = new javax.swing.JButton();
        btn_modificar_trab = new javax.swing.JButton();
        btn_registrar_trab = new javax.swing.JButton();
        btn_buscar_trab = new javax.swing.JButton();
        txt_apellidos_trab = new javax.swing.JTextField();
        txt_telefono_trab = new javax.swing.JTextField();
        box_departamento_trab = new javax.swing.JComboBox<>();
        btn_eliminar_trab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Empleados");

        jPanel1.setBackground(new java.awt.Color(116, 223, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Gestión de Empleados");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID_trabajador:");

        txt_id_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_id_trab.setToolTipText("");
        txt_id_trab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_id_trab.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_nombre_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nombre_trab.setToolTipText("");
        txt_nombre_trab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_nombre_trab.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        txt_email_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_email_trab.setToolTipText("");
        txt_email_trab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_email_trab.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Departamento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teléfono:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");

        btn_ver_empleado.setBackground(new java.awt.Color(65, 237, 206));
        btn_ver_empleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ver_empleado.setText("Ver Lista de Empleados");
        btn_ver_empleado.setBorder(new javax.swing.border.MatteBorder(null));
        btn_ver_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_empleadoActionPerformed(evt);
            }
        });

        btn_modificar_trab.setBackground(new java.awt.Color(65, 237, 206));
        btn_modificar_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_modificar_trab.setText("Modificar");
        btn_modificar_trab.setBorder(new javax.swing.border.MatteBorder(null));
        btn_modificar_trab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_trabActionPerformed(evt);
            }
        });

        btn_registrar_trab.setBackground(new java.awt.Color(65, 237, 206));
        btn_registrar_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_registrar_trab.setText("Registrar");
        btn_registrar_trab.setBorder(new javax.swing.border.MatteBorder(null));
        btn_registrar_trab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_trabActionPerformed(evt);
            }
        });

        btn_buscar_trab.setBackground(new java.awt.Color(65, 237, 206));
        btn_buscar_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_buscar_trab.setText("Buscar");
        btn_buscar_trab.setBorder(new javax.swing.border.MatteBorder(null));
        btn_buscar_trab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_trabActionPerformed(evt);
            }
        });

        txt_apellidos_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_apellidos_trab.setToolTipText("");
        txt_apellidos_trab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_apellidos_trab.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_telefono_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_telefono_trab.setToolTipText("");
        txt_telefono_trab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 3));
        txt_telefono_trab.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        box_departamento_trab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--selecionar una opcion--", "Administración", "Atención al Cliente", "Préstamos y Devoluciones", "Catalogación", "Mantenimiento", "TI (Tecnología de la Información)", "Logística" }));
        box_departamento_trab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 176, 155), 2));

        btn_eliminar_trab.setBackground(new java.awt.Color(65, 237, 206));
        btn_eliminar_trab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_eliminar_trab.setText("Eliminar");
        btn_eliminar_trab.setBorder(new javax.swing.border.MatteBorder(null));
        btn_eliminar_trab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_trabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_registrar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modificar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nombre_trab)
                                    .addComponent(txt_id_trab)
                                    .addComponent(txt_apellidos_trab)
                                    .addComponent(txt_email_trab)
                                    .addComponent(txt_telefono_trab)
                                    .addComponent(box_departamento_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_eliminar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ver_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellidos_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_departamento_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ver_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar_trab, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ver_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ver_empleadoActionPerformed

    private void btn_modificar_trabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_trabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificar_trabActionPerformed

    private void btn_registrar_trabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_trabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrar_trabActionPerformed

    private void btn_buscar_trabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_trabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_trabActionPerformed

    private void btn_eliminar_trabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_trabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminar_trabActionPerformed

    public JComboBox<String> getBox_departamento_trab() {
        return box_departamento_trab;
    }

    public void setBox_departamento_trab(JComboBox<String> box_departamento_trab) {
        this.box_departamento_trab = box_departamento_trab;
    }

    public JButton getBtn_buscar_trab() {
        return btn_buscar_trab;
    }

    public void setBtn_buscar_trab(JButton btn_buscar_trab) {
        this.btn_buscar_trab = btn_buscar_trab;
    }

    public JButton getBtn_eliminar_trab() {
        return btn_eliminar_trab;
    }

    public void setBtn_eliminar_trab(JButton btn_eliminar_trab) {
        this.btn_eliminar_trab = btn_eliminar_trab;
    }

    public JButton getBtn_modificar_trab() {
        return btn_modificar_trab;
    }

    public void setBtn_modificar_trab(JButton btn_modificar_trab) {
        this.btn_modificar_trab = btn_modificar_trab;
    }

    public JButton getBtn_registrar_trab() {
        return btn_registrar_trab;
    }

    public void setBtn_registrar_trab(JButton btn_registrar_trab) {
        this.btn_registrar_trab = btn_registrar_trab;
    }

    public JButton getBtn_ver_empleado() {
        return btn_ver_empleado;
    }

    public void setBtn_ver_empleado(JButton btn_ver_empleado) {
        this.btn_ver_empleado = btn_ver_empleado;
    }

    public JTextField getTxt_apellidos_trab() {
        return txt_apellidos_trab;
    }

    public void setTxt_apellidos_trab(JTextField txt_apellidos_trab) {
        this.txt_apellidos_trab = txt_apellidos_trab;
    }

    public JTextField getTxt_email_trab() {
        return txt_email_trab;
    }

    public void setTxt_email_trab(JTextField txt_email_trab) {
        this.txt_email_trab = txt_email_trab;
    }

    public JTextField getTxt_id_trab() {
        return txt_id_trab;
    }

    public void setTxt_id_trab(JTextField txt_id_trab) {
        this.txt_id_trab = txt_id_trab;
    }

    public JTextField getTxt_nombre_trab() {
        return txt_nombre_trab;
    }

    public void setTxt_nombre_trab(JTextField txt_nombre_trab) {
        this.txt_nombre_trab = txt_nombre_trab;
    }

    public JTextField getTxt_telefono_trab() {
        return txt_telefono_trab;
    }

    public void setTxt_telefono_trab(JTextField txt_telefono_trab) {
        this.txt_telefono_trab = txt_telefono_trab;
    }

   

   



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_departamento_trab;
    private javax.swing.JButton btn_buscar_trab;
    private javax.swing.JButton btn_eliminar_trab;
    private javax.swing.JButton btn_modificar_trab;
    private javax.swing.JButton btn_registrar_trab;
    private javax.swing.JButton btn_ver_empleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_apellidos_trab;
    private javax.swing.JTextField txt_email_trab;
    private javax.swing.JTextField txt_id_trab;
    private javax.swing.JTextField txt_nombre_trab;
    private javax.swing.JTextField txt_telefono_trab;
    // End of variables declaration//GEN-END:variables
}
