/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JButton;

/**
 *
 * @author souls
 */
public class MenuPrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalVista
     */
    public MenuPrincipalVista() {
        initComponents();
    }

    public JButton getBtn_gestion_libros() {
        return btn_gestion_libros;
    }

    public void setBtn_gestion_libros(JButton btn_gestion_libros) {
        this.btn_gestion_libros = btn_gestion_libros;
    }

    public JButton getBtn_gestion_pagos() {
        return btn_gestion_pagos;
    }

    public void setBtn_gestion_pagos(JButton btn_gestion_pagos) {
        this.btn_gestion_pagos = btn_gestion_pagos;
    }

    public JButton getBtn_gestion_prestamos() {
        return btn_gestion_prestamos;
    }

    public void setBtn_gestion_prestamos(JButton btn_gestion_prestamos) {
        this.btn_gestion_prestamos = btn_gestion_prestamos;
    }

    public JButton getBtn_gestion_socios() {
        return btn_gestion_socios;
    }

    public void setBtn_gestion_socios(JButton btn_gestion_socios) {
        this.btn_gestion_socios = btn_gestion_socios;
    }

    public JButton getBtn_gestion_empleados() {
        return btn_gestion_empleados;
    }

    public void setBtn_gestion_empleados(JButton btn_gestion_empleados) {
        this.btn_gestion_empleados = btn_gestion_empleados;
    }

    public JButton getBtn_cerrar_sesion() {
        return btn_cerrar_sesion;
    }

    public void setBtn_cerrar_sesion(JButton btn_cerrar_sesion) {
        this.btn_cerrar_sesion = btn_cerrar_sesion;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_gestion_prestamos = new javax.swing.JButton();
        btn_gestion_libros = new javax.swing.JButton();
        btn_gestion_socios = new javax.swing.JButton();
        btn_gestion_pagos = new javax.swing.JButton();
        btn_gestion_empleados = new javax.swing.JButton();
        btn_cerrar_sesion = new javax.swing.JButton();
        btn_registrar_usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de gestion de bibliotecas");
        setBackground(new java.awt.Color(116, 223, 190));

        jPanel2.setBackground(new java.awt.Color(116, 223, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Sistema de Gestión de Bibliotecas");

        btn_gestion_prestamos.setBackground(new java.awt.Color(65, 237, 206));
        btn_gestion_prestamos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gestion_prestamos.setText("Gestión de Préstamos");
        btn_gestion_prestamos.setBorder(new javax.swing.border.MatteBorder(null));
        btn_gestion_prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_prestamosActionPerformed(evt);
            }
        });

        btn_gestion_libros.setBackground(new java.awt.Color(65, 237, 206));
        btn_gestion_libros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gestion_libros.setText("Gestión de Libros");
        btn_gestion_libros.setBorder(new javax.swing.border.MatteBorder(null));
        btn_gestion_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_librosActionPerformed(evt);
            }
        });

        btn_gestion_socios.setBackground(new java.awt.Color(65, 237, 206));
        btn_gestion_socios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gestion_socios.setText("Gestión de Socios");
        btn_gestion_socios.setBorder(new javax.swing.border.MatteBorder(null));
        btn_gestion_socios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_sociosActionPerformed(evt);
            }
        });

        btn_gestion_pagos.setBackground(new java.awt.Color(65, 237, 206));
        btn_gestion_pagos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gestion_pagos.setText("Gestión de Pagos");
        btn_gestion_pagos.setBorder(new javax.swing.border.MatteBorder(null));
        btn_gestion_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_pagosActionPerformed(evt);
            }
        });

        btn_gestion_empleados.setBackground(new java.awt.Color(65, 237, 206));
        btn_gestion_empleados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_gestion_empleados.setText("Gestión de Empleados");
        btn_gestion_empleados.setBorder(new javax.swing.border.MatteBorder(null));
        btn_gestion_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_empleadosActionPerformed(evt);
            }
        });

        btn_cerrar_sesion.setBackground(new java.awt.Color(186, 187, 191));
        btn_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cerrar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar_sesion.setText("Cerrar Sesion");
        btn_cerrar_sesion.setBorder(new javax.swing.border.MatteBorder(null));
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });

        btn_registrar_usuario.setBackground(new java.awt.Color(65, 237, 206));
        btn_registrar_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_registrar_usuario.setText("Registrar Usuario");
        btn_registrar_usuario.setBorder(new javax.swing.border.MatteBorder(null));
        btn_registrar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_gestion_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_gestion_libros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_gestion_socios, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_gestion_prestamos, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                .addComponent(btn_gestion_empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_registrar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cerrar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gestion_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gestion_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gestion_prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gestion_socios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gestion_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_cerrar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gestion_sociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_sociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gestion_sociosActionPerformed

    private void btn_gestion_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gestion_librosActionPerformed

    private void btn_gestion_prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_prestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gestion_prestamosActionPerformed

    private void btn_gestion_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_pagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gestion_pagosActionPerformed

    private void btn_gestion_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_empleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_gestion_empleadosActionPerformed

    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    private void btn_registrar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrar_usuarioActionPerformed

    public JButton getBtn_registrar_usuario() {
        return btn_registrar_usuario;
    }

    public void setBtn_registrar_usuario(JButton btn_registrar_usuario) {
        this.btn_registrar_usuario = btn_registrar_usuario;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JButton btn_gestion_empleados;
    private javax.swing.JButton btn_gestion_libros;
    private javax.swing.JButton btn_gestion_pagos;
    private javax.swing.JButton btn_gestion_prestamos;
    private javax.swing.JButton btn_gestion_socios;
    private javax.swing.JButton btn_registrar_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
